version: '3.8'

services:
  mmysql:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_tracker
    ports:
      - "3307:3306"

  spring-boot-app:
    build: .
    environment:
      DATABASE_URL: jdbc:mysql://mmysql:3306/expense_tracker 
      DATABASE_USERNAME: root 
      DATABASE_PASSWORD: root 
      EMAIL_USERNAME: 17niranjanyadav@gmail.com 
      EMAIL_PASSWORD: "wkdi qkrc sglu svoo" 
      FRONTEND_URL: http://localhost:5173
    ports:
      - "8081:8080"
    depends_on:
      - mmysql

